name: publish
on:
  push:
jobs:
  build:
    name: compile book from markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install pandoc
        run: |
          curl -fLo /tmp/pandoc-2.10.1-1-amd64.deb https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
          sudo dpkg -i /tmp/pandoc-2.10.1-1-amd64.deb
      - name: Install npm packages
        run: npm ci
      - name: Build website
        run: bash build.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: 'github-pages'
          path: 'book'
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
